### ISSUE TITLE
봇 추가 안되는 이슈 관련 공지

### ISSUE THREAD

**Issue by MadeGOD** [Archive-Discord/battle-bot-slash#24]
배틀봇이 빠른 성장으로 인해 서버수가 일반봇 최대치인 250서버 이상으로 추가가 안되게 제한되었습니다. 해당 이슈는 봇 인증 문제임으로 현재로썬 해결이 불가능한 이슈입니다.

이로 인해 **휴먼서버**들을 통지 없이 자동 퇴장이 될수 있을수 있습니다.

> 휴먼 서버란?
- 몇개월 동안 사용되지 않은 서버
- 테스트 목적으로 참여된 서버
- 개인서버 및 소규모 서버(봇 제외 1명이하 서버)
- 배틀봇 이용도가 적은서버

**Comment by kiss8981** [comment]
현재 모든 인텐트 승인으로 해당 이슈는 닫도록 하겠습니다
